export const GET_CURRENT_WEATHER_START = 'GET_CURRENT_WEATHER_START';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';

export const GET_FUTURE_WEATHER_START = 'GET_FUTURE_WEATHER_START';
export const GET_FUTURE_WEATHER_SUCCESS = 'GET_FUTURE_WEATHER_SUCCESS';
export const GET_FUTURE_WEATHER_FAILED = 'GET_FUTURE_WEATHER_FAILED';