export const GET_WEATHER_START = 'GET_WEATHER_START';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';
export const GET_FUTURE_WEATHER = 'GET_FUTURE_WEATHER';
export const GET_FUTURE_WEATHER_FAILED = 'GET_FUTURE_WEATHER_FAILED';